name: Snyk Delta All Projects

on:
  workflow_dispatch:
  push: {}
  pull_request:
    branches: main
jobs:
  snyk-delta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Snyk & Snyk-Delta  
        run: npm install -g snyk snyk-delta
      - name: Run snyk_delta_all_projects.sh
        run: |
          chmod +x snyk_delta_all_projects.sh
          ./snyk_delta_all_projects.sh --exclude=scripts
        shell: bash
    
env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}