name: Snyk Delta All Projects

on:
  push: {}

jobs:
  snyk-delta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run snyk_delta_all_projects.sh
        run: ./snyk_delta_all_projects.sh --exclude=scripts

env:
  # Store your Snyk token as a secret named 'SNYK_TOKEN'
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}