name: Snyk Delta All Projects

on:
  workflow_dispatch:
  push: {}
  pull_request:
    branches: main

jobs:
  snyk-delta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: List files in repository for debugging
        run: ls -al
        shell: bash

      - name: Install Snyk & Snyk-Delta
        run: |
            npm install -g snyk snyk-delta  
            snyk auth $SNYK_TOKEN
      - name: Run snyk_delta_all_projects.sh
        run: ./snyk-delta-all-projects.sh --exclude=scripts --json-file-output=results.json
        shell: bash
        continue-on-error: true

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
